import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

import '../models/event_definition.dart';

/// Dartコード生成器
class DartGenerator {
  final DartFormatter _formatter = DartFormatter();

  /// イベント定義からDartコードを生成
  String generate(List<EventDefinition> events) {
    final specs = <Spec>[
      _buildFileHeader(),
    ];

    // イベントがある場合のみenumと拡張を生成
    if (events.isNotEmpty) {
      specs.add(_buildEventNameEnum(events));
      specs.addAll(events.map(_buildEventClass));
      specs.add(_buildAnalyticsServiceExtension(events));
    }

    final library = Library((b) {
      b.body.addAll(specs);
    });

    final emitter = DartEmitter(
      allocator: Allocator(),
      useNullSafetySyntax: true,
    );
    final code = library.accept(emitter).toString();

    return _formatter.format(code);
  }

  Code _buildFileHeader() {
    return Code('''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by ga_sync
// ignore_for_file: type=lint

''');
  }

  Enum _buildEventNameEnum(List<EventDefinition> events) {
    return Enum((b) {
      b
        ..name = 'GaEventName'
        ..docs.add('/// GAイベント名の列挙型')
        ..values.addAll(
          events.map((e) => EnumValue((v) {
                v.name = e.enumValue;
                if (e.description != null) {
                  v.docs.add('/// ${e.description}');
                }
              })),
        );
    });
  }

  Class _buildEventClass(EventDefinition event) {
    return Class((b) {
      b
        ..name = '${event.className}Event'
        ..docs.add('/// ${event.description ?? event.eventName} イベント');

      // フィールド
      for (final param in event.parameters) {
        b.fields.add(Field((f) {
          f
            ..name = param.fieldName
            ..type = Reference(param.dartType)
            ..modifier = FieldModifier.final$;
        }));
      }

      // コンストラクタ
      b.constructors.add(Constructor((c) {
        c.constant = true;
        for (final param in event.parameters) {
          c.optionalParameters.add(Parameter((p) {
            p
              ..name = param.fieldName
              ..named = true
              ..required = param.isRequired
              ..toThis = true;
          }));
        }
      }));

      // イベント名プロパティ
      b.methods.add(Method((m) {
        m
          ..name = 'eventName'
          ..type = MethodType.getter
          ..returns = Reference('String')
          ..lambda = true
          ..body = Code("'${event.eventName}'");
      }));

      // toParametersメソッド
      b.methods.add(Method((m) {
        m
          ..name = 'toParameters'
          ..returns = Reference('Map<String, dynamic>')
          ..body = _buildToParametersBody(event);
      }));
    });
  }

  Code _buildToParametersBody(EventDefinition event) {
    if (event.parameters.isEmpty) {
      return const Code('return {};');
    }

    final buffer = StringBuffer('return {\n');
    for (final param in event.parameters) {
      buffer.writeln("  '${param.name}': ${param.fieldName},");
    }
    buffer.write('};');

    return Code(buffer.toString());
  }

  Extension _buildAnalyticsServiceExtension(List<EventDefinition> events) {
    return Extension((b) {
      b
        ..name = 'GaEventExtensions'
        ..on = Reference('GaEventName')
        ..docs.add('/// GaEventNameの拡張メソッド');

      // rawNameプロパティ
      b.methods.add(Method((m) {
        m
          ..name = 'rawName'
          ..type = MethodType.getter
          ..returns = Reference('String')
          ..body = _buildRawNameBody(events);
      }));
    });
  }

  Code _buildRawNameBody(List<EventDefinition> events) {
    final buffer = StringBuffer('return switch (this) {\n');
    for (final event in events) {
      buffer.writeln("  GaEventName.${event.enumValue} => '${event.eventName}',");
    }
    buffer.write('};');

    return Code(buffer.toString());
  }
}
