import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

import '../models/event_definition.dart';

/// Dart code generator
class DartGenerator {
  final DartFormatter _formatter = DartFormatter();

  /// Generate Dart code from event definitions
  String generate(List<EventDefinition> events) {
    final specs = <Spec>[
      _buildFileHeader(),
    ];

    // Only generate enum and extension if there are events
    if (events.isNotEmpty) {
      specs.add(_buildEventNameEnum(events));
      specs.addAll(events.map(_buildEventClass));
      specs.add(_buildAnalyticsServiceExtension(events));
    }

    final library = Library((b) {
      b.body.addAll(specs);
    });

    final emitter = DartEmitter(
      allocator: Allocator(),
      useNullSafetySyntax: true,
    );
    final code = library.accept(emitter).toString();

    return _formatter.format(code);
  }

  Code _buildFileHeader() {
    return const Code('''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by ga_sync
// ignore_for_file: type=lint

''');
  }

  Enum _buildEventNameEnum(List<EventDefinition> events) {
    return Enum((b) {
      b
        ..name = 'GaEventName'
        ..docs.add('/// GA event name enum')
        ..values.addAll(
          events.map(
            (e) => EnumValue((v) {
              v.name = e.enumValue;
              if (e.description != null) {
                v.docs.add('/// ${e.description}');
              }
            }),
          ),
        );
    });
  }

  Class _buildEventClass(EventDefinition event) {
    return Class((b) {
      b
        ..name = '${event.className}Event'
        ..docs.add('/// ${event.description ?? event.eventName} event');

      // Fields
      for (final param in event.parameters) {
        b.fields.add(
          Field((f) {
            f
              ..name = param.fieldName
              ..type = Reference(param.dartType)
              ..modifier = FieldModifier.final$;
          }),
        );
      }

      // Constructor
      b.constructors.add(
        Constructor((c) {
          c.constant = true;
          for (final param in event.parameters) {
            c.optionalParameters.add(
              Parameter((p) {
                p
                  ..name = param.fieldName
                  ..named = true
                  ..required = param.isRequired
                  ..toThis = true;
              }),
            );
          }
        }),
      );

      // Event name property
      b.methods.add(
        Method((m) {
          m
            ..name = 'eventName'
            ..type = MethodType.getter
            ..returns = const Reference('String')
            ..lambda = true
            ..body = Code("'${event.eventName}'");
        }),
      );

      // toParameters method
      b.methods.add(
        Method((m) {
          m
            ..name = 'toParameters'
            ..returns = const Reference('Map<String, dynamic>')
            ..body = _buildToParametersBody(event);
        }),
      );
    });
  }

  Code _buildToParametersBody(EventDefinition event) {
    if (event.parameters.isEmpty) {
      return const Code('return {};');
    }

    final buffer = StringBuffer('return {\n');
    for (final param in event.parameters) {
      buffer.writeln("  '${param.name}': ${param.fieldName},");
    }
    buffer.write('};');

    return Code(buffer.toString());
  }

  Extension _buildAnalyticsServiceExtension(List<EventDefinition> events) {
    return Extension((b) {
      b
        ..name = 'GaEventExtensions'
        ..on = const Reference('GaEventName')
        ..docs.add('/// GaEventName extension methods');

      // rawName property
      b.methods.add(
        Method((m) {
          m
            ..name = 'rawName'
            ..type = MethodType.getter
            ..returns = const Reference('String')
            ..body = _buildRawNameBody(events);
        }),
      );
    });
  }

  Code _buildRawNameBody(List<EventDefinition> events) {
    final buffer = StringBuffer('return switch (this) {\n');
    for (final event in events) {
      buffer
          .writeln("  GaEventName.${event.enumValue} => '${event.eventName}',");
    }
    buffer.write('};');

    return Code(buffer.toString());
  }
}
